### ISSUE TITLE
can't download the extension

### ISSUE THREAD

**Issue by sleetdrop** [mac-cain13/xdebug-helper-for-safari#10]
both in apple extension download page and the wiki page here, I can't download the extension.

**Comment by mac-cain13** [comment]
Thanks for reporting this error, it seems that the URL broke while this repository was moved. I'll fix this asap!

You can install the plugin by downloading it from: http://mac-cain13.github.com/xdebug-helper-for-safari/xdebug-helper.safariextz

**Comment by sleetdrop** [comment]
thanks, it works now

**Comment by mac-cain13** [comment]
Great, thanks for the heads-up!
