### ISSUE TITLE
Support for 2.3

### ISSUE THREAD

**Issue by benmatselby** [mac-cain13/xdebug-helper-for-safari#11]
Hi there @mac-cain13 

Are you planning on supporting 2.3 as per Derick's comments here: https://github.com/benmatselby/xdebug-toggler/issues/3

If you are, then I will point my repo to this one and deprecate my plugin.

**Comment by mac-cain13** [comment]
I'm open to add it and probably will do this myself sometime. But it is a low priority feature to add for me, so don't expect anything soon. :)
